name: Generate ASCII Dragon

on:
  push

jobs:
  gen-ascii:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cowsay
        run: sudo apt-get install cowsay -y

      - name: excute ASCII dragon script
        run: ./gen-ascii-script.sh

    